var zxCarApplyWinAdd;
var zxCarApplyFormAdd;
function addZxCarApply(){
	initZxCarApplyFormAdd();
	zxCarApplyWinAdd = Ext.create('Ext.Window',{
		layout:'fit',
		width:1050,
		height:600,
		maximizable:true,
		minimizable:true,
		animateTarget:document.body,
		plain:true,
		modal:true,
		title:'添加信息',
		listeners:{
			minimize:function(win,opts){
				if(!win.collapse()){
					win.collapse();
				}else{
					win.expand();
				}
			}
		},
		items:zxCarApplyFormAdd,
		buttons:[{
			text:'保存',
			itemId:'save',
			handler:function(button){
				submitForm(zxCarApplyFormAdd,'../zxCarApplyController/addZxCarApply',grid,zxCarApplyWinAdd,false,true);
			}
		},{
			text:'关闭',
			itemId:'close',
			handler:function(button){
				button.up('window').close();
			}
		}]
	});
	zxCarApplyWinAdd.show();
	Ext.getCmp('apply_user_id').setValue(xt_userinfo_id);
	Ext.getCmp('apply_user_name').setValue(sys_pt_user_name);
	Ext.getCmp('zxcardepart').setValue(sys_pt_departinfo_name);
}
function initZxCarApplyFormAdd(){
	zxCarApplyFormEditFieldSet = Ext.create('Ext.form.FieldSet',{
		anchor:'100%',
		title:'申请人信息',
		items:[
        {
			layout:"column",
			items:[
				{
					fieldLabel:'申请人',
					xtype:'textfield',
					name:'apply_user_id',
					hidden:true,
					id:'apply_user_id',
					maxLength:255,
					width:320
				},
				{
					fieldLabel:'申请人',
					xtype:'textfield',
					id:'apply_user_name',
					allowBlank:false,
					readOnly:true,
					maxLength:255,
					width:320
				},
				{
					fieldLabel:'部门',
					xtype:'textfield',
					name:'zxcardepart',
					id:'zxcardepart',
					maxLength:255,
					allowBlank:false,
					width:320,
					readOnly:true
				},
				{
					fieldLabel:'申请类型',
					xtype:"combo",
					queryMode:'local', 
					store:zx_car_apply_type,
					triggerAction:"all",
		            editable:false,
					allowBlank:false,
		            emptyText:'请选择',
		            valueField:"xt_data_dictionary_value",
		            displayField:"xt_data_dictionary_name",
					name:'apply_type',
					maxLength:32,
					width:320
				},
				{
					fieldLabel:'申请状态',
					xtype:"combo",
					queryMode:'local', 
					store:zx_car_apply_status,
					triggerAction:"all",
					hidden:true,
		            editable:false,
					allowBlank:false,
		            emptyText:'请选择',
		            valueField:"xt_data_dictionary_value",
		            displayField:"xt_data_dictionary_name",
					name:'state',
					value : '1',
					maxLength:32,
					width:320
				}
			]
		}
	]
	});
	zxCarBaseInfoFormEditFieldSet = Ext.create('Ext.form.FieldSet',{
		anchor:'100%',
		title:'基础信息',
		items:[
        {
			layout:"column",
			items:[
				{
					fieldLabel:'用车时间始',
					xtype:'datetimefield',
					format:'Y-m-d H:i:s',
					name:'apply_time_begin',
					allowBlank:false,
					maxLength:255,
					width:320,
					anchor:'100%'
				},
				{
					fieldLabel:'用车时间末',
					xtype:'datetimefield',
					format:'Y-m-d H:i:s',
					name:'apply_time_end',
					allowBlank:false,
					maxLength:255,
					width:320,
					anchor:'100%'
				},
				{
					fieldLabel:'用车事由',
					xtype:'textfield',
					name:'user_car_reason',
					allowBlank:false,
					maxLength:255,
					width:320,
					anchor:'100%'
				}
			]
		},{
			layout:"column",
			items:[
				{
					fieldLabel:'目的地',
					xtype:'textfield',
					name:'apply_car_address',
					allowBlank:false,
					maxLength:255,
					width:320
				},
				{
					fieldLabel:'外出人员',
					xtype:'textfield',
					name:'user_car_person',
					allowBlank:false,
					maxLength:255,
					width:650,
					anchor:'100%'
				}
			]
		},{
			fieldLabel:'携带物品',
			xtype:'textareafield',
			name:'comment',
			maxLength:255,
			width:980
		}
	]
	});
	
	zxCarApplyFormAdd = Ext.create('Ext.FormPanel',{
		xtype:'form',
		waitMsgTarget:true,
		defaultType:'textfield',
		autoScroll:true,
		/**新方法使用开始**/
		scrollable:true,
		scrollable:'x',
		scrollable:'y',
		/**新方法使用结束**/
		fieldDefaults:{
			labelWidth:70,
			labelAlign:'left',
			flex:1,
			margin:'2 5 4 5'
		},
		items:[
	       zxCarApplyFormEditFieldSet,
	       zxCarBaseInfoFormEditFieldSet
		]
	});
}


