var zxExpressdeliveryWinAdd;
var zxExpressdeliveryFormAdd;
var applyUserFieldSet;
var zxExpressdeliveryFieldSet;
function addZxExpressdelivery(){
	initZxExpressdeliveryFormAdd();
	zxExpressdeliveryWinAdd = Ext.create('Ext.Window',{
		layout:'fit',
		width:800,
		height:470,
		maximizable:false,
		minimizable:false,
		animateTarget:document.body,
		plain:true,
		modal:true,
		title:'添加信息',
		listeners:{
			minimize:function(win,opts){
				if(!win.collapse()){
					win.collapse();
				}else{
					win.expand();
				}
			}
		},
		items:zxExpressdeliveryFormAdd,
		buttons:[{
			text:'申请',
			itemId:'save',
			handler:function(button){
				submitForm(zxExpressdeliveryFormAdd,'../zxExpressdeliveryController/addZxExpressdelivery',grid,zxExpressdeliveryWinAdd,false,true);
			}
		},{
			text:'关闭',
			itemId:'close',
			handler:function(button){
				button.up('window').close();
			}
		}]
	});
	zxExpressdeliveryWinAdd.show();
	Ext.getCmp('apply_user_id').setValue(xt_userinfo_id);
	Ext.getCmp('apply_user_name').setValue(sys_pt_user_name);
	Ext.getCmp('zxcardepart').setValue(sys_pt_departinfo_name);
	
}
function initZxExpressdeliveryFormAdd(){
	applyUserFieldSet = Ext.create('Ext.form.FieldSet',{
		anchor:'100%',
		title:'申请人信息',
		items:[
        {
			layout:"column",
			items:[
				{
					fieldLabel:'申请人',
					xtype:'textfield',
					name:'apply_user_id',
					hidden:true,
					id:'apply_user_id',
					maxLength:32,
					width:320
				},
				{
					fieldLabel:'申请人',
					xtype:'textfield',
					id:'apply_user_name',
					name:'apply_user_name',
					allowBlank:false,
					readOnly:true,
					maxLength:255,
					width:350
				},
				{
					fieldLabel:'部门',
					xtype:'textfield',
					name:'zxcardepart',
					id:'zxcardepart',
					maxLength:255,
					width:350,
					readOnly:true
				}
			]
		}
	]
	});
	zxExpressdeliveryFieldSet = Ext.create('Ext.form.FieldSet',{
		anchor:'100%',
		title:'快递信息',
		items:[
		{
			fieldLabel:'申请状态',
			xtype:"combo",
			queryMode:'local', 
			store:zx_expressdelivery_status,
			triggerAction:"all",
			hidden:true,
            editable:false,
			allowBlank:false,
            emptyText:'请选择',
            valueField:"xt_data_dictionary_value",
            displayField:"xt_data_dictionary_name",
			name:'status',
			value : '1',
			maxLength:32,
			width:320
		},
		{
			layout:"column",
			items:[
			{
				fieldLabel:'公司名称',
				xtype:'textfield',
				name:'company',
				maxLength:255,
				width:710
			}
			]
		},
		{
			layout:"column",
			items:[
			{
				fieldLabel:'地址',
				xtype:'textfield',
				name:'address',
				maxLength:255,
				width:710
			}
			]
		},
		{
			layout:"column",
			items:[
			{
				fieldLabel:'收件人',
				xtype:'textfield',
				name:'addressee',
				maxLength:255,
				width:350
			},
			{
				fieldLabel:'收件人电话',
				xtype:'textfield',
				name:'addressee_concat',
				maxLength:255,
				width:350
			}
			]
		},
		{
			layout:"column",
			items:[
			{
				fieldLabel:'所寄物品',
				xtype:'textfield',
				name:'goods',
				maxLength:255,
				width:710
			}
			]
		},
		{
			layout:"column",
			items:[
			{
				fieldLabel:'快递类型',
				xtype:"combo",
				queryMode:'local', 
				store:zx_expressdelivery_type,
				triggerAction:"all",
	            editable:false,
				allowBlank:false,
	            emptyText:'请选择',
	            valueField:"xt_data_dictionary_value",
	            displayField:"xt_data_dictionary_name",
				name:'type',
				maxLength:32,
				width:710
			}
			]
		}
	]
	});
	zxExpressdeliveryFormAdd = Ext.create('Ext.FormPanel',{
		xtype:'form',
		waitMsgTarget:true,
		defaultType:'textfield',
		autoScroll:true,
		/**新方法使用开始**/
		scrollable:true,
		scrollable:'x',
		scrollable:'y',
		/**新方法使用结束**/
		fieldDefaults:{
			labelWidth:70,
			labelAlign:'left',
			flex:1,
			margin:'2 5 4 5'
		},
		items:[
			applyUserFieldSet,
			zxExpressdeliveryFieldSet
		]
	});
}
