var zxSixSContentWinDetail;
var zxSixSContentFormDetail;
function detailZxSixSContent(id){
	initZxSixSContentFormDetail();
	zxSixSContentWinDetail = Ext.create('Ext.Window',{
		layout:'fit',
		width:1100,                    
		height:500,
		maximizable:true,
		minimizable:true,
		animateTarget:document.body,
		plain:true,
		modal:true,
		title:'详细信息',
		listeners:{
			minimize:function(win,opts){
				if(!win.collapse()){
					win.collapse();
				}else{
					win.expand();
				}
			}
		},
		items:zxSixSContentFormDetail,
		buttons:[{
			text:'关闭',
			itemId:'close',
			handler:function(button){
				button.up('window').close();
			}
		}]
	});
	zxSixSContentWinDetail.show();
	initFileRight2('problem_pic','problem_pic_pic',2,1);
	initFileRight2('result_pic','result_pic_pic',2,1);
	
	loadFormData(zxSixSContentFormDetail,'../zxSixSContentController/getZxSixSContentById?id='+ id);
}
function initZxSixSContentFormDetail(){
	initDetailFieldItems();
	zxSixSContentFormDetail = Ext.create('Ext.FormPanel',{
		xtype:'form',
		waitMsgTarget:true,
		defaultType:'textfield',
		autoScroll:true,
		/**新方法使用开始**/
		scrollable:true,
		scrollable:'x',
		scrollable:'y',
		/**新方法使用结束**/
		fieldDefaults:{
			labelWidth:70,
			labelAlign:'left',
			flex:1,
			readOnly:true,
			margin:'2 5 4 5'
		},
		items:[
		{
			fieldLabel:'ID',
			xtype:'textfield',
			hidden:true,
			name:'id',
			allowBlank:false,
			maxLength:32,
			anchor:'100%'
		},
		{
			fieldLabel:'six_sID',
			xtype:'textfield',
			name:'six_s_id',
			maxLength:32,
			hidden:true,
			anchor:'100%'
		},
		zxField1,zxField2,
		{
			fieldLabel:'参考照片',
			xtype:'textfield',
			hidden:true,
			id:'problem_pic',
			name:'problem_pic',
			maxLength:32,
			anchor:'100%'
		},
		{
			title:'参考照片',
			xtype:'fieldset',
			items:{
				xtype:'box', 
				id:'problem_pic_pic', 
				margin:'2 5 4 70', 
				autoEl:{
					tag:'img',
					src:bsdefimg
				}
			}
		},
		{
			fieldLabel:'改善结果',
			xtype:'textfield',
			hidden:true,
			id:'result_pic',
			name:'result_pic',
			maxLength:32,
			anchor:'100%'
		},
		{
			title:'改善结果',
			xtype:'fieldset',
			items:{
				xtype:'box', 
				id:'result_pic_pic', 
				margin:'2 5 4 70', 
				autoEl:{
					tag:'img',
					onclick:"optupload('result_pic','result_pic_pic',1)",
					src:bsdefimg
				}
			}
		},
		{
			fieldLabel:'创建日期',
			xtype:'textfield',
			name:'create_date',
			maxLength:32,
			hidden:true,
			anchor:'100%'
		}
		]
	});
}

function initDetailFieldItems(){
	zxField1 = Ext.create('Ext.form.FieldSet',{
		anchor:'100%',
		title:'基本信息',
		items:[
        {
			layout:"column",
			items:[
			{
				columnWidth:.25,
				items:[
				{ 
					fieldLabel:'检查场所',
					xtype:'combo',
					emptyText:'请选择',
					store:six_s_check_place,
					mode:'local',
					triggerAction:'all',
					editable:false,
					hiddenName:'place_id',
					valueField:'xt_data_dictionary_id',
					displayField:'xt_data_dictionary_name',
					name:'place_id',
					maxLength:32,
					allowBlank:false,
					anchor:'100%'
				}]
			},
			{
				columnWidth:.25,
				items:[{
					fieldLabel:'责任部门',
					xtype:'treepicker',
					displayField:'text',
					anchor:'60%',
					hiddenName:'dep_id',
					name:'dep_id',
					minPickerHeight:200,
					maxHeight:200,
					editable:false,
					allowBlank:false,
					store:zx_dep,
					allowBlank:false,
					anchor:'100%'
				}]
			},
			{
				columnWidth:.25,
				items:[{
					fieldLabel:'责任人',
					xtype:'textfield',
					id:'user_id',
					name:'user_id',
					maxLength:32,
					hidden:true,
					allowBlank:false,
					anchor:'100%'
				},
				{
					fieldLabel:'责任人',
					xtype:'textfield',
					id:'user_realname',
					name:'user_realname',
					maxLength:32,
					allowBlank:false,
					editable:false,
					anchor:'100%'
				}]
			},
			{
				columnWidth:.25,
				items:[{
					fieldLabel:'完成期限',
					xtype:'datetimefield',
					format:'Y-m-d',
					name:'end_date',
					maxLength:19,
					allowBlank:false,
					anchor:'30%'
				}]
			}
			]
		}
	]
	});
	
	zxField2 = Ext.create('Ext.form.FieldSet',{
		anchor:'100%',
		title:'说明',
		items:[
	        { 
				fieldLabel:'不符合项说明',
				xtype:'textareafield',
				name:'problem',
				maxLength:256,
				editable:false,
				anchor:'100%'
			},
			{
				fieldLabel:'改善措施',
				xtype:'textareafield',
				name:'measure',
				maxLength:256,
				editable:false,
				anchor:'100%'
			}
        ]
	});
}