function updateZxMeetingUserinfo(meeting_id){
	initXtUserinfoGrid(meeting_id);
	initXtUserinfoGrided(meeting_id);
	initXtDpPanel();
	reGetWidthAndHeight();
	zxMeetingUserWin = Ext.create('top.Ext.Window',{
		layout:'border', 
		maximizable:true,
		minimizable:true,
		maximized:true,
		plain:true,
		modal:true,
		width:clientWidth,                    
		height:clientHeight, 
		headerPosition:'top',
		title:'修改参会人员',
		listeners:{
			minimize:function(win,opts){
				if(!win.collapse()){
					win.collapse();
				}else{
					win.expand();
				}
			}
		},
		items:[xtDpPanel,
			  {
			  	region:'center',
			  	items:[
			  	{
			  		items:xtUserinfoGrid
			  	},
			  	{
			  		items:xtUserinfoGrided
			  	}
			  	]
			  }
			  ],
		buttons:[{
				text:'关闭',
				itemId:'close',
				handler:function(button){
					button.up('window').close();
				} 
			}
			]
	});
	zxMeetingUserWin.setTitle("参会人员选择");
	zxMeetingUserWin.show();
}