var zxMaterialClassifyWinAdd;
var zxMaterialClassifyFormAdd;
function addZxMaterialClassify(){
	
	initZxMaterialClassifyFormAdd();
	zxMaterialClassifyWinAdd = Ext.create('Ext.Window',{
		layout:'fit',
		width:600,
		height:400,
		maximizable:true,
		minimizable:true,
		animateTarget:document.body,
		plain:true,
		modal:true,
		title:'添加信息',
		listeners:{
			minimize:function(win,opts){
				if(!win.collapse()){
					win.collapse();
				}else{
					win.expand();
				}
			}
		},
		items:zxMaterialClassifyFormAdd,
		buttons:[{
			text:'保存',
			itemId:'save',
			handler:function(button){
				submitForm(zxMaterialClassifyFormAdd,'../zxMaterialClassifyController/addZxMaterialClassify',grid,zxMaterialClassifyWinAdd,false,true);
			}
		},{
			text:'关闭',
			itemId:'close',
			handler:function(button){
				button.up('window').close();
			}
		}]
	});
	zxMaterialClassifyWinAdd.show();
	
}
function initZxMaterialClassifyFormAdd(){
	zxMaterialClassifyFormAdd = Ext.create('Ext.FormPanel',{
		xtype:'form',
		waitMsgTarget:true,
		defaultType:'textfield',
		autoScroll:true,
		/**新方法使用开始**/
		scrollable:true,
		scrollable:'x',
		scrollable:'y',
		/**新方法使用结束**/
		fieldDefaults:{
			labelWidth:100,
			labelAlign:'left',
			flex:1,
			margin:'2 5 4 5'
		},
		items:[{
			fieldLabel:'上级分类',
			xtype:'treepicker',
			displayField:'text',
			anchor:'100%',
			hiddenName:'classify_parentId',
			name:'classify_parentId',
			minPickerHeight:200,
			maxHeight:200,
			editable:false,
			allowBlank:false,
			rootVisible:true,
			store:Ext.create('Ext.data.TreeStore',{
				fields:['id','text'],
				root:{
					text:'一级分类',
					id:'0',
					expanded:true
				},
				proxy:{
					type:'ajax',
					url:'../zxMaterialClassifyController/getZxMaterialClassifyTree',
					reader:{
						type:'json'
					}
				}
			})
		},
		{
			fieldLabel:'分类名称',
			xtype:'textfield',
			name:'classify_short_name',
			allowBlank:false,
			maxLength:200,
			anchor:'100%'
		},
		{
			fieldLabel:'全名',
			xtype:'textfield',
			name:'classify_name',
			allowBlank:false,
			maxLength:200,
			anchor:'100%'
		},
		{
			fieldLabel:'分类编号',
			xtype:'textfield',
			name:'classify_num',
			allowBlank:false,
			maxLength:100,
			anchor:'100%'
		},
		{
			fieldLabel:'是否存在子叶',
			xtype:'combo',
			emptyText:'请选择',
			store:zx_material_classify_leaf,
			mode:'local',
			triggerAction:'all',
			editable:false,
			allowBlank: false,
			hiddenName:'classify_leaf',
			valueField:'value',
			displayField:'text',
			name:'classify_leaf',
			maxLength:1,
			anchor:'100%'
		},
		{
			fieldLabel:'状态',
			xtype:'combo',
			emptyText:'请选择',
			store:zx_material_classify_delete,
			mode:'local',
			triggerAction:'all',
			editable:false,
			allowBlank: false,
			hiddenName:'classify_isdelete',
			valueField:'value',
			displayField:'text',
			name:'classify_isdelete',
			maxLength:2,
			anchor:'100%'
		},
		{
			fieldLabel:'创建时间',
			xtype:'textfield',
			name:'classify_time',
			maxLength:20,
			hidden:true,
			anchor:'100%'
		},
		{
			fieldLabel:'排序',
			xtype:'numberfield',
			value:'0',
			allowBlank: false,
			name:'classify_sort',
			maxLength:10,
			anchor:'100%'
		}
		]
	});
}
