var zxExpressdeliveryWinDetail;
var zxExpressdeliveryFormDetail;
function detailZxExpressdelivery(){
	var record = grid.getSelectionModel().selected;
	initZxExpressdeliveryFormDetail();
	zxExpressdeliveryWinDetail = Ext.create('Ext.Window',{
		layout:'fit',
		width:800,
		height:500,
		maximizable:false,
		minimizable:false,
		animateTarget:document.body,
		plain:true,
		modal:true,
		title:'明细信息',
		listeners:{
			minimize:function(win,opts){
				if(!win.collapse()){
					win.collapse();
				}else{
					win.expand();
				}
			}
		},
		items:zxExpressdeliveryFormDetail
	});
	zxExpressdeliveryWinDetail.show();
	loadFormDataCallBack(zxExpressdeliveryFormDetail,'../zxExpressdeliveryController/getZxExpressdeliveryById?id='+ record.items[0].data.id,callFnDetail);
}
function initZxExpressdeliveryFormDetail(){
	applyUserFieldSet = Ext.create('Ext.form.FieldSet',{
		anchor:'100%',
		title:'申请信息',
		items:[
        {
			layout:"column",
			items:[
				{
					fieldLabel:'标识ID',
					xtype:'textfield',
					hidden:true,
					name:'id',
					allowBlank:false,
					maxLength:32,
					hidden:true,
					anchor:'100%'
				},
				{
					fieldLabel:'申请时间',
					xtype:'datetimefield',
					format:'Y-m-d H:i:s',
					name:'apply_time',
					maxLength:19,
					hidden:true
				},
				{
					fieldLabel:'申请人',
					xtype:'textfield',
					name:'apply_user_id',
					hidden:true,
					id:'apply_user_id',
					maxLength:32,
					width:320
				},
				{
					fieldLabel:'申请人',
					xtype:'textfield',
					id:'apply_user_name',
					name:'apply_user_name',
					allowBlank:false,
					readOnly:true,
					maxLength:255,
					width:350
				},
				{
					fieldLabel:'部门',
					xtype:'textfield',
					name:'zxcardepart',
					id:'zxcardepart',
					maxLength:255,
					width:350,
					readOnly:true
				}
			]
		},
		{
			fieldLabel:'申请状态',
			xtype:"combo",
			queryMode:'local', 
			store:zx_expressdelivery_status,
			triggerAction:"all",
			hidden:true,
            editable:false,
			allowBlank:false,
            emptyText:'请选择',
            valueField:"xt_data_dictionary_value",
            displayField:"xt_data_dictionary_name",
			name:'status',
			maxLength:32,
			width:320
		},
		{
			layout:"column",
			items:[
			{
				fieldLabel:'公司名称',
				xtype:'textfield',
				name:'company',
				readOnly:true,
				maxLength:255,
				width:710
			}
			]
		},
		{
			layout:"column",
			items:[
			{
				fieldLabel:'地址',
				xtype:'textfield',
				name:'address',
				readOnly:true,
				maxLength:255,
				width:710
			}
			]
		},
		{
			layout:"column",
			items:[
			{
				fieldLabel:'收件人',
				xtype:'textfield',
				name:'addressee',
				readOnly:true,
				maxLength:255,
				width:350
			},
			{
				fieldLabel:'收件人电话',
				xtype:'textfield',
				name:'addressee_concat',
				readOnly:true,
				maxLength:255,
				width:350
			}
			]
		},
		{
			layout:"column",
			items:[
			{
				fieldLabel:'所寄物品',
				xtype:'textfield',
				name:'goods',
				readOnly:true,
				maxLength:255,
				width:710
			}
			]
		},
		{
			layout:"column",
			items:[
			{
				fieldLabel:'快递类型',
				xtype:"combo",
				queryMode:'local', 
				store:zx_expressdelivery_type,
				triggerAction:"all",
	            editable:false,
				readOnly:true,
				allowBlank:false,
	            emptyText:'请选择',
	            valueField:"xt_data_dictionary_value",
	            displayField:"xt_data_dictionary_name",
				name:'type',
				maxLength:32,
				width:710
			}
			]
		}
	]
	});
	zxExpressdeliveryFieldSet = Ext.create('Ext.form.FieldSet',{
		anchor:'100%',
		title:'登记信息',
		items:[
			{
				layout:"column",
				items:[
				{
					fieldLabel:'快递单号',
					xtype:'textfield',
					name:'num',
					readOnly:true,
					maxLength:255,
					width:230
				},
				{
					fieldLabel:'快递金额',
					xtype:'numberfield',
					name:'money',
					maxLength:20,
					decimalPrecision:2, // 精确到小数点后两位
					maxValue:1000,// 最大值
					minValue:1, // 最小值
					readOnly:true,
					width:230
				},
				{
					fieldLabel:'快递日期',
					xtype:'datetimefield',
					format:'Y-m-d H:i:s',
					readOnly:true,
					editable:false,
					name:'send_time',
					maxLength:19,
					width:230
				}
				]
			}
			
		]
	});
	zxExpressdeliveryFormDetail = Ext.create('Ext.FormPanel',{
		xtype:'form',
		waitMsgTarget:true,
		defaultType:'textfield',
		autoScroll:true,
		/**新方法使用开始**/
		scrollable:true,
		scrollable:'x',
		scrollable:'y',
		/**新方法使用结束**/
		fieldDefaults:{
			labelWidth:70,
			labelAlign:'left',
			flex:1,
			margin:'2 5 4 5'
		},
		items:[
			applyUserFieldSet,
			zxExpressdeliveryFieldSet
		]
	});
}
function callFnDetail(form, action){
	var applyUser = action.result.data.applyUser;
	if(null != applyUser){
		Ext.getCmp('apply_user_name').setValue(applyUser.xt_userinfo_realName);
		Ext.getCmp('zxcardepart').setValue(applyUser.xt_departinfo_name);
	}
}