var zxWorkpieceWinEdit;
var zxWorkpieceFormEdit;
function updateZxWorkpiece(){
	var record = grid.getSelectionModel().selected;
	if(record.length == 0){
		msgTishi('请选择要修改的一项！');
		return;
	}
	initZxWorkpieceFormEdit();
	zxWorkpieceWinEdit = Ext.create('Ext.Window',{
		layout:'fit',
		width:600,
		height:400,
		maximizable:true,
		minimizable:true,
		animateTarget:document.body,
		plain:true,
		modal:true,
		title:'编辑信息',
		listeners:{
			minimize:function(win,opts){
				if(!win.collapse()){
					win.collapse();
				}else{
					win.expand();
				}
			}
		},
		items:zxWorkpieceFormEdit,
		buttons:[{
			text:'保存',
			itemId:'save',
			handler:function(button){
				submitForm(zxWorkpieceFormEdit,'../zxWorkpieceController/updateZxWorkpiece',grid,zxWorkpieceWinEdit,false,true);
			}
		},{
			text:'关闭',
			itemId:'close',
			handler:function(button){
				button.up('window').close();
			}
		}]
	});
	zxWorkpieceWinEdit.show();
	
	loadFormData(zxWorkpieceFormEdit,'../zxWorkpieceController/getZxWorkpieceById?id='+ record.items[0].data.id);
}
function initZxWorkpieceFormEdit(){
	zxWorkpieceFormEdit = Ext.create('Ext.FormPanel',{
		xtype:'form',
		waitMsgTarget:true,
		defaultType:'textfield',
		autoScroll:true,
		/**新方法使用开始**/
		scrollable:true,
		scrollable:'x',
		scrollable:'y',
		/**新方法使用结束**/
		fieldDefaults:{
			labelWidth:70,
			labelAlign:'left',
			flex:1,
			margin:'2 5 4 5'
		},
		items:[
		{
			fieldLabel:'工件ID',
			xtype:'textfield',
			hidden:true,
			name:'id',
			allowBlank:false,
			maxLength:32,
			hidden:true,
			anchor:'100%'
		},
		{
			fieldLabel:'项目',
			xtype:'combo',
			emptyText:'请选择',
			store:zx_project_id_combo,
			mode:'local',
			triggerAction:'all',
			editable:false,
			hiddenName:'project_id',
			valueField:'id',
			displayField:'name',
			name:'project_id',
			maxLength:32,
			anchor:'100%',
			listeners:{
                change:function(){
                	sfiValue(zxWorkpieceFormEdit,'project_name_update',this.rawValue);
                }
            }
		},
		{
			fieldLabel:'项目名称',
			xtype:'textfield',
			name:'project_name',
			itemId:'project_name_update',
			maxLength:255,
			hidden:true,
			anchor:'100%'
		},
		{
			fieldLabel:'组别',
			xtype:'textfield',
			name:'zubie',
			maxLength:100,
			anchor:'100%'
		},
		{
			fieldLabel:'工件编号',
			xtype:'textfield',
			name:'num',
			maxLength:100,
			anchor:'100%'
		},
		{
			fieldLabel:'工件名称',
			xtype:'textfield',
			name:'name',
			maxLength:100,
			anchor:'100%'
		},
		{
			fieldLabel:'单位',
			xtype:'textfield',
			name:'unit',
			maxLength:50,
			anchor:'100%'
		}
		]
	});
}
